# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
#USE="-X"

CPU_FLAGS_X86=" aes avx avx2 avx512_bf16 avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi avx512vl bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

PYTHON_TARGETS="python3_13 python3_14"
PYTHON_SINGLE_TARGET="python3_14"

MAKEOPTS="-j12 -l18"
FEATURES="parallel-fetch"
#EMERGE_DEFAULT_OPTS="--jobs=3"

ACCEPT_LICENSE="* @FREE @BINARY-REDISTRIBUTABLE @EULA"


GENTOO_MIRRORS="https://in.mirrors.cicku.me/gentoo/ \
    https://mirrors.nxtgen.com/gentoo-mirror/gentoo-source/ \
    https://gentoo.mirrors.ovh.net/gentoo-distfiles/ \
    https://ariel.in.ext.planetunix.net/pub/gentoo/ \
    https://jp.mirrors.cicku.me/gentoo/ \
    https://mirror.hashy0917.net/gentoo/ \
    https://ftp.iij.ad.jp/pub/linux/gentoo/ \
    https://ftp.jaist.ac.jp/pub/Linux/Gentoo/ \
    https://repo.jing.rocks/gentoo \
    https://kale.jp.ext.planetunix.net/pub/gentoo/ \
    https://ftp.riken.jp/Linux/gentoo/ \
    https://mirror.yandex.ru/gentoo-distfiles/ \
    https://kr.mirrors.cicku.me/gentoo/ \
    https://ftp.kaist.ac.kr/pub/gentoo/ \
    https://mirror.keiminem.com/gentoo/ \
    https://ftp.lanet.kr/pub/gentoo/ \
    https://es.mirrors.cicku.me/gentoo/"
